name: qr_scanner
description: A Flutter QR Code and Barcode Scanner/Generator with AdMob Integration
publish_to: "none"

version: 0.1.0+11

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  share_plus: ^11.0.0
  syncfusion_flutter_barcodes: ^30.1.41
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1
  package_info_plus: ^8.3.0
  add_2_calendar: ^3.0.1
  flutter_contacts: ^1.1.9+2
  permission_handler: ^12.0.1
  intl: ^0.20.2
  wifi_iot: ^0.3.19+2
  mobile_scanner: ^7.0.1
  image_picker: ^1.1.2
  google_mlkit_barcode_scanning: ^0.14.1
  flutter_colorpicker: ^1.1.0
  shared_preferences: ^2.5.3
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icon/icon.png
